Add "No results found" utility to search dropdown
InternetHealthReport/ihr-website pull request #708
Opened 2023-12-20 10:08 UTC by Animesh239

close: #676 

## Description

added: no results found for "value" in the search-bars

## Screenshots : (for networkSearchBar)
![Screenshot 2023-12-20 151901](https://github.com/InternetHealthReport/ihr-website/assets/115821028/d0782ad2-de64-473c-90ce-4c0d297a3614)
![Screenshot 2023-12-20 151929](https://github.com/InternetHealthReport/ihr-website/assets/115821028/48a940b1-6fd5-40f3-bd26-0e6a97d26e50)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2023-12-20 11:12 UTC, Animesh239 commented
there is a bug in my PR , will fix it soon...

2023-12-20 19:09 UTC, Animesh239 commented
@dpgiakatos you can review this PR

2023-12-22 10:55 UTC, dpgiakatos requested changes
Hello,
This pull request aims to resolve the issue when we encounter no results in a search bar. It includes modifications in two components:
1. **NetworkSearchBar.vue**: This component manages the search functionality for networks or countries. The changes made have been tested successfully and work without any issues. However, it's worth noting that this component may be deprecated and replaced with another one after the completion of the IYP integration, which is currently in progress.
2. **LocationSerachBar.vue**: This component handles the search for an AS network. The changes made have also been tested, but they cause a crash in the application. I've attached a screenshot with the test case and the logs from the browser console.
![image](https://github.com/InternetHealthReport/ihr-website/assets/36899728/2f82d108-10a2-43f7-8719-aa14b6b4a277)
[#708-LocationSearchBar.log](https://github.com/InternetHealthReport/ihr-website/files/13751635/708-LocationSearchBar.log)

In summary, this pull request cannot be merged without first addressing the issues mentioned in this review.

2023-12-23 10:53 UTC, dpgiakatos commented
When you have addressed the issue, please request a review.

2023-12-23 13:04 UTC, Animesh239 commented
hey @dpgiakatos 
I made the necessary changes to the locationSearchBar file in the prev commit.
Please review my PR and let me know if any additional changes are needed.

2023-12-23 13:22 UTC, dpgiakatos commented on src/components/search/LocationSearchBar.vue
> +import { ref, inject, watch, defineProps, defineEmits } from 'vue'
defineProps and defineProps are a compiler macro and no longer needs to be imported.

2023-12-23 13:24 UTC, dpgiakatos commented on src/components/search/LocationSearchBar.vue
> +const emits = defineEmits(['select'])
Since this component is the last one that uses the select emit function, this function should be initiated here. Please undo this change.

2023-12-23 13:41 UTC, dpgiakatos requested changes
In the previous review, we requested the contributor to address certain issues. The contributor has made changes in response to the previous review, and this review pertains to those changes.

It involves modifications in one component:

1. **LocationSerachBar.vue**: The changes have been tested using the same test cases as in the initial review, and unfortunately, the application crashed again. I have attached the new logs from the browser console.
[708-LocationSerachBar.log](https://github.com/InternetHealthReport/ihr-website/files/13759202/708-LocationSerachBar.log)

We kindly ask the contributor to perform thorough testing of the proposed changes before requesting another review.

In summary, this pull request cannot be merged without first addressing the issues mentioned in this review.

2024-01-15 15:45 UTC, Animesh239 commented
hey @dpgiakatos, thanku for providing for logs.
I think the logs are indicating some error in the plotly graph.
In networkDelayChart.vue line.293
```vue
    // Add null if there is missing data
    let prevDate = new Date(trace.x.slice(-1)[0]).getTime()
    let currDate = new Date(elem.timebin).getTime()
    if (currDate > prevDate + timeResolution + 1) {
      trace.y.push(null)
      trace.x.push(elem.timbin)
    }
``` 
there is a typo error `trace.x.push(elem.timbin)`
it should be`trace.x.push(elem.timebin)`

I think this should resolve the crashing...

2024-01-15 21:22 UTC, dpgiakatos commented
Before reviewing the changes, have you tested using the provided test case?

2024-01-16 08:18 UTC, Animesh239 commented
below are the screenshots of browser console for localhost
![Screenshot (97)](https://github.com/InternetHealthReport/ihr-website/assets/115821028/dd742a17-bbaa-4486-8f37-1b527e23c579)
![Screenshot (98)](https://github.com/InternetHealthReport/ihr-website/assets/115821028/a081559d-4814-41f8-a9e5-ce6bc3119370)


in summary, the changes are not causing any errors in the browser console.

2024-03-01 11:08 UTC, dpgiakatos requested changes
You should rebase your repository from the dev branch as there are some conflicts, and proceed with addressing the issues highlighted in the files you changed in this PR. Also, make sure to check the code for any errors before submitting it. Thank you!

2024-03-01 11:08 UTC, dpgiakatos commented on src/components/search/LocationSearchBar.vue
> +          name: `No results found for "${value}"`,
Replace `No results found for "${value}"` with `No results found`

2024-03-01 11:08 UTC, dpgiakatos commented on src/components/search/LocationSearchBar.vue
> +          label: `No results found for "${value}"`,
Replace `No results found for "${value}"` with `No results found`

2024-03-01 11:08 UTC, dpgiakatos commented on src/components/search/NetworkSearchBar.vue
This file no longer exists.

2024-03-04 18:22 UTC, closed without merging