added world map in country pages
InternetHealthReport/ihr-website pull request #741
Opened 2024-02-18 10:29 UTC by Animesh239

close #740 

## Description

Added the world map to select countries from the map

## Features

- When a country is clicked, it redirects to the respective country report page
- While hovering, country names are displayed
- In the mobile view, the decision was made not to display the map to prevent excessive shrinking. Shrinking the map significantly would compromise the user experience, as it could make the map details difficult to discern or interact with effectively on smaller screens.

## Screenshots (if appropriate):
![Screenshot (104)](https://github.com/InternetHealthReport/ihr-website/assets/115821028/f5b09d24-fc51-418a-83cd-74dc64b6bfd9)

2024-02-19 06:42 UTC, dpgiakatos commented
We've updated the architecture for the country pages, introducing several new features. Please hold off on integrating these changes until PR #719 is merged. Once that's done, you'll need to update your corresponding page accordingly. We'll then proceed with a review. Thanks for your patience!

2024-02-29 06:57 UTC, dpgiakatos requested changes
You should rebase your repository from the `dev` branch as there are some conflicts, and proceed with addressing the issues highlighted in the files you changed in this PR. Thank you!

2024-02-29 06:57 UTC, dpgiakatos commented on src/components/maps/WorldMap.vue
Please utilize the ReactiveChart component instead of creating a new Plotly instance. You can refer to other examples in the components/map folder to see how plots are created.

2024-02-29 06:57 UTC, dpgiakatos commented on src/views/Countries.vue
The map is too large, making it difficult for users to access the examples easily. Consider creating a better layout where both the map and the examples are easily accessible to users.

2024-02-29 22:27 UTC, Animesh239 commented
## updated layout
![image](https://github.com/InternetHealthReport/ihr-website/assets/115821028/297fb7b9-b4b4-4014-8523-53e5fd16ffbe)

2024-02-29 23:18 UTC, dpgiakatos commented
I think it's better to add a map button next to the search icon (first the map icon, then the search icon) in the search bar, which will open the map in a dialog. This map button will only be available if the `noCountry` parameter on the `SearchBar` component is `false`.

2024-03-02 06:38 UTC, dpgiakatos commented
Returning to this pull request since #757 (which was a duplicate) has been closed as incomplete due to numerous file changes, which will impact the repository history.

2024-03-04 14:39 UTC, dpgiakatos commented
You have made changes in 129 files because you rebased from the master branch, which is incorrect. Please refer to our contribution guide in the README.md file. The master branch is reserved for production, not for development. The development branch is named dev.

2024-03-04 14:45 UTC, dpgiakatos commented
Some steps that might help you:
1. Fork the `dev` branch.
2. Apply the changes to fix the corresponding issue.
3. Submit a pull request to the `dev` branch.

2024-03-04 18:22 UTC, closed without merging

2024-03-04 18:33 UTC, Animesh239 commented
> Some steps that might help you:
> 
> 1. Fork the `dev` branch.
> 2. Apply the changes to fix the corresponding issue.
> 3. Submit a pull request to the `dev` branch.

Thanks, @dpgiakatos,I will move this PR to a new PR.
Currently closing it as the fork behavior was from the master branch.