Users info UI
InternetHealthReport/ihr-website pull request #765
Opened 2024-03-13 03:49 UTC by 0xAnon0602

Added the User Information with [RIPE API](https://stat.ripe.net/) and [IYP data](https://iyp.iijlab.net/) as discussed in #758 

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/3d252d8c-1722-4364-bcb5-0e05ebae7d4f)

2024-03-14 08:03 UTC, dpgiakatos commented
Some improvements for the UI, before I review your PR. Please, add connection information below the Global Report button. Optimize the card layout for compactness by removing unnecessary space. Also, include a line to separate the button from the card.

2024-03-14 11:00 UTC, 0xAnon0602 commented
Got it 
Will work on the changes you suggested

2024-03-14 11:25 UTC, dpgiakatos commented
Once you change the UI please upload a screenshot here.

2024-03-14 11:36 UTC, 0xAnon0602 commented
@dpgiakatos 
You mean by moving that card in the way I showed in the image right ?
![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/5654a55a-b97c-48a7-97d0-751b2e7a63b9)

2024-03-18 06:21 UTC, dpgiakatos commented
Do we have any progress on this PR?

2024-03-18 06:23 UTC, 0xAnon0602 commented
Hey sorry for the delay was busy during the weekend
Will probably push the new changes by the EOD

2024-03-18 09:43 UTC, 0xAnon0602 commented
@dpgiakatos 
I was able to do the changes as you said 
Let me know if any more changes are required in the UI

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/b99a081a-f672-481c-a668-2859fc5bdbf1)

2024-03-18 12:34 UTC, dpgiakatos commented
The card should have the same width with the button and the title. Also, as I have mentioned before, you should have a line, which will separate the button and the card. Furthermore, the card should follow the buttons style; the corners should not be round. The same goes with the background, make it transparent and the font color should be white (like the button and the title). Remove the icon in cards title. The card’s border should be white.

2024-03-18 13:40 UTC, 0xAnon0602 commented
@dpgiakatos 

Is this what you were looking for ?

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/6fde7a72-aaeb-4c8d-90a9-92c0fda80182)

2024-03-18 14:51 UTC, dpgiakatos commented
It's almost there, but some more modifications should be made. The corners are still round, and the card's width is slightly bigger than the button. So, let's remove the card's radius and ensure that the card, button, and title have the same width. Additionally, remove the underline from 'Your Connections', make it uppercase, and add a border to the card's title (see example in the attachment). Finally, the card's text should be like the example I have attached

<img width="552" alt="image" src="https://github.com/InternetHealthReport/ihr-website/assets/36899728/37647289-22ff-4196-b07d-51b82303633e">

2024-03-18 17:31 UTC, 0xAnon0602 commented
@dpgiakatos 
Added the changes you asked 
Let me know if any further change is required )

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/06d528de-b872-44d7-a46a-c3125920aec4)

2024-03-19 02:18 UTC, dpgiakatos requested changes
This pull request introduces a new feature, which is a nice addition. However, before approving it, there are several issues that need to be addressed. The contributor should focus on resolving the issues mentioned in this review before proceeding further.

2024-03-19 02:18 UTC, dpgiakatos commented on src/components/UserInfo.vue
When the screen shrinks, the component disappears, which it should not.

2024-03-19 02:18 UTC, dpgiakatos commented on src/views/Home.vue
The recent changes have altered the current UI layout, which needs to be fixed. The UI layout should remain consistent and not change unexpectedly. Please revert the changes to restore the UI to its previous state as in the dev branch. Additionally, ensure that the addition of the UserInfo component does not affect the layout of the landing page.

---PR 765---
![image](https://github.com/InternetHealthReport/ihr-website/assets/36899728/eb0ca49e-ec60-4ce8-9dfb-74f26076e0e5)
---
---Dev branch---
![image](https://github.com/InternetHealthReport/ihr-website/assets/36899728/10cc09f4-994d-477a-a8f3-576e225c13a2)
---

2024-03-19 08:25 UTC, 0xAnon0602 commented
@dpgiakatos 

Did all the changes as you asked me and this is the updated UI

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/bfcd1a2b-6163-4f14-9b62-44fd290732ff)

Let me know if I should open a new PR if this one is conflicting with the `dev` branch

2024-03-19 08:48 UTC, 0xAnon0602 commented
@dpgiakatos 
I've linked the final PR in #769

2024-03-21 05:29 UTC, closed without merging