User Info UI
InternetHealthReport/ihr-website pull request #769
Opened 2024-03-19 08:47 UTC by 0xAnon0602

@dpgiakatos 

Here is the final version of #765 with all the changes you asked for 

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/d0ebabdb-5cfa-4be6-a55f-948f2b4d5a08)

2024-03-21 05:54 UTC, dpgiakatos requested changes
Please refrain from opening multiple PRs for the same issue in the future. This practice makes it challenging to track the history of changes and follow the conversation effectively. Additionally, it is crucial to thoroughly test all current functionalities on the website before submitting any code changes. This ensures that your modifications do not inadvertently break existing features. For instance, changing the color in the your connection table affects the color scheme in corresponding tables in the network, country, or prefix overview pages. Please address these issues accordingly. Thank you!

2024-03-21 05:54 UTC, dpgiakatos commented on src/components/UserInfo.vue
> +.q-table tbody td
It's incorrect to overload the tags because this change affects all the tbody td elements across the entire site. Consequently, this alteration has broken the styles in other parts of the website. Create a class instead and do not use !important.

2024-03-21 05:54 UTC, dpgiakatos commented on src/components/UserInfo.vue
> +.link
We want the links to be visibly distinguishable as links. Therefore, please retain the underline for the links.

2024-03-21 05:54 UTC, dpgiakatos commented on src/components/UserInfo.vue
> +                    <td >IP</td>
Alight the text right.

2024-03-21 05:54 UTC, dpgiakatos commented on src/components/UserInfo.vue
> +                    <td>AS</td>
Alight the text right.

2024-03-21 05:54 UTC, dpgiakatos commented on src/components/UserInfo.vue
> +                    <td>PREFIX</td>
Alight the text right.

2024-03-21 05:54 UTC, dpgiakatos commented on src/components/UserInfo.vue
> +                    <td>COUNTRY</td>
Alight the text right.

2024-03-21 05:54 UTC, dpgiakatos commented on src/components/UserInfo.vue
These changes affect the styles of the entire website and need to be rectified. Additionally, responsiveness is not functioning properly. Quasar components such as cards and markup-tables typically handle responsiveness by default. I am uncertain why you have overridden these default functionalities with `@media` queries. I suggest removing these queries and allowing the Quasar library to handle responsiveness. If there are any reasons why this cannot work, please let us discuss them here.

2024-03-21 05:54 UTC, dpgiakatos commented on src/components/UserInfo.vue
> +@media(max-width 600px)
This line should be removed. Please refer to the general comment for this file.

2024-03-21 05:54 UTC, dpgiakatos commented on src/components/UserInfo.vue
> +@media(max-width 315px)
This line should be removed. Please refer to the general comment for this file.

2024-03-21 05:54 UTC, dpgiakatos commented on src/views/Home.vue
When shrinking the screen, the global report button has an animation for responsiveness, while the line and your connection card do not. So, we need to either remove the animation from the button or add the corresponding animation to the line and the card. I suggest removing the animation from the button.

2024-03-21 07:20 UTC, 0xAnon0602 commented on src/components/UserInfo.vue
The media queries was used for the title and button on the landing screen to optimize it for the small screen 
So I've used to match their width and everything 

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/cdd9eae5-615d-4349-ba9b-58f6abca4f31)

2024-03-21 07:28 UTC, 0xAnon0602 commented
@dpgiakatos 
Sorry for the trouble. 
I've fixed all the issues you stated above, except the media query one. 
I'm waiting for your feedback on that

2024-03-21 08:46 UTC, dpgiakatos commented on src/components/UserInfo.vue
> These changes affect the styles of the entire website and need to be rectified. Additionally, responsiveness is not functioning properly. Quasar components such as **cards** and **markup-tables** typically handle responsiveness by default. I am uncertain why you have overridden these default functionalities with @media queries. I suggest removing these queries and allowing the Quasar library to handle responsiveness. If there are any reasons why this cannot work, please let us discuss them here.

As I have already stated, if you are using Quasar components such as **cards** and **markup-tables**, the responsiveness will be handled by the library. In your code, you are creating a card using CSS instead of using the [QCard](https://quasar.dev/vue-components/card/) component from Quasar. Please refer to the Quasar documentation to learn how to create a card. It provides plenty of examples of how you can use and customize it. Thus, you should wrap the markup-tables with the QCard component and remove all unnecessary styles.

2024-03-21 09:50 UTC, 0xAnon0602 commented
I think this commit should fix the above issues )

2024-03-22 03:52 UTC, dpgiakatos commented
It has some issues with the coding structure and the functionalities, and I'm confident that we can remove the `@media` queries. I believe it would be easier for me to address these issues. I'll merge it and follow up with a PR that addresses these issues.

2024-03-22 03:52 UTC, merged