Peeringdb fix
InternetHealthReport/ihr-website pull request #775
Opened 2024-03-27 03:38 UTC by 0xAnon0602

Fixes #772 

For AS 55836, it now shows like this 

![image](https://github.com/InternetHealthReport/ihr-website/assets/71931823/84151796-5c10-4172-bd11-2ae1ff1f2d38)

2024-03-27 10:09 UTC, dpgiakatos requested changes
Please address the issues mentioned below. Thanks.

2024-03-27 10:09 UTC, dpgiakatos commented on src/components/networks/as/ASOverview.vue
> +    if(pdbid.value) externalLink = `${references.value[key]}/${pdbid.value}`
Delete the if statement

2024-03-27 10:09 UTC, dpgiakatos commented on src/components/networks/as/ASOverview.vue
>    } else if (key === 'peeringdb.com') {
Add here the below condition. E.g.:
```
...
} else if (key === 'peeringdb.com' && pdbid.value) {
...
```

2024-03-27 10:23 UTC, 0xAnon0602 commented
@dpgiakatos 
Fixed it with recent commit )

2024-03-28 01:30 UTC, dpgiakatos approved these changes
Thanks

2024-03-28 01:31 UTC, merged