Fixed Prefix on Network Topology
InternetHealthReport/ihr-website pull request #846
Opened 2024-09-30 05:42 UTC by 0xAnon0602

Added feature to automatic shift IPv version based on input 

https://github.com/user-attachments/assets/6bba2519-d104-4317-af52-ac816428d7b1

2024-10-01 10:21 UTC, dpgiakatos requested changes
Please follow our code styling for the if statements.
Thank you.

2024-10-01 10:26 UTC, dpgiakatos commented
Maybe in the input placeholder is better to have `AS or Prefix` instead of `Search`. What do you think?

2024-10-01 10:28 UTC, dpgiakatos commented on src/components/charts/NetworkTopologyChart.vue
> +  if (input.includes('.') || input.includes(':')) {
Both IPv4 and IPv6 prefixes contain a '/', so you do not need to include conditions for '.' and ':'.

2024-10-01 10:30 UTC, dpgiakatos commented on src/components/charts/NetworkTopologyChart.vue
> +  if(newValue.includes('.')) ipModel.value = "IPv4"
Here is better to have one if (isPrefix) and then the other two ifs.

2024-10-01 13:18 UTC, 0xAnon0602 commented
> Maybe in the input placeholder is better to have `AS or Prefix` instead of `Search`. What do you think?

Yeah that's actually a good idea to let user know what exactly to input

2024-10-01 13:22 UTC, 0xAnon0602 commented
@dpgiakatos Did all the changes you asked for in the new PR )

2024-10-02 00:51 UTC, dpgiakatos approved these changes
Thanks

2024-10-02 00:52 UTC, merged